from .modify_surfdatamap import apply_replacement_perc, tree_aggregation, tree_separation
from .plot import dict_to_legend, map_lonlatdistribution, basic_pft_map, plot_boreal_pfts, basic_line_plot, plot_individual_cumulative, ax_map_properties, cut_extent_Orthographic, dominant_vegetation, discrete_mapping_elements, plot_dominant_vegetation
